=== Hamzakardate/XTML/Hamza_Kardate_XML_DTD_XSD/XSD/emails.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="emails">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="email" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="head">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="date"/>
                    <xs:element type="xs:string" name="from"/>
                    <xs:element type="xs:string" name="to"/>
                    <xs:element name="copy" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="type" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="subject" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="body">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="message"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="attachement" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="file" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Hamzakardate/XTML/Hamza_Kardate_XML_DTD_XSD/XSD/emails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails [
<!ENTITY FSDM "Faculté des sciences dhar el mahraz"> 
]>
<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="emails.xsd">
	<email>
		<head>
			<date>18/10/2006</date>
			<from>Zinedine</from>
			<to>Ahmed</to>
			<copy>Toi</copy>
			<copy type="BCC">Lui</copy>
			<subject>Reunion</subject>
		</head>
		<body>
			<message>Une réunion aura lieu Jeudi Inchaallah à 10h à la &FSDM;.</message>
		</body>
	</email>
	
	<email>
		<head>
			<date>12/12/2006</date>
			<from>me</from>
			<to>you</to>
		</head>
		<body>
			<message>The journey was successful. Great photos were taken. An example is sent with this email. See you soon.</message>
		</body>
		<attachement file="photo1.jpg"/>
		<attachement file="photo2.jpg"/>
		<attachement file="photo3.jpg"/>
		
	</email>
</emails>
