=== Hamzakardate/XTML/Hamza_Kardate_XML_DTD_XSD/XSD/liste.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="liste">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="étudiant" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nom"/>
              <xs:element type="xs:string" name="prénom"/>
              <xs:element type="xs:byte" name="age"/>
              <xs:element name="tél" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:int">
                      <xs:attribute type="xs:string" name="type" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="email"/>
              <xs:element name="photo">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="source" use="optional"/>
                      <xs:attribute type="xs:byte" name="hauteur" use="optional"/>
                      <xs:attribute type="xs:byte" name="largeur" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="description" minOccurs="0"/>
              <xs:element name="CV" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="file"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="code" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:short" name="année"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Hamzakardate/XTML/Hamza_Kardate_XML_DTD_XSD/XSD/liste.xml
<?xml version ="1.0" ?>
<liste année = "2021" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="liste.xsd">
	<étudiant  code="E1">
		<nom>Moujtahid</nom>
		<prénom>Moujidd</prénom>
		<age>25</age>
		<email>moujtahid@fsdmfes.ac.ma</email>
		<photo source="moujtahid.jpg" hauteur="80" largeur="80" />
		<description>Moujtahid Moujidd est un étudiant brillant. Il est majeur de sa promotion. Après avoir obtenu son bac sciences Math avec la mention très bien. Il s'est inscrit à la faculté des Science Dhar Mehraz. Après avoir obtenu la licence, il a été accèpté en DESS GI</description>
	</étudiant>
	<étudiant code="E2">
		<nom>Kaddouri</nom>
		<prénom>Kaddour</prénom>
		<age>26</age>
		
		<tél type="portable">070333333</tél>
		<email>kaddouri@fsdmfes.ac.ma</email>
		<photo source="kaddouri.jpg"></photo>
		<description>Kaddouri Kaddour a suivi toutes ses années de la licence au sein de la FSDM. Ses compétences remarquables lui ont permis de suivre ses études supérieures spécilisées</description>
	</étudiant>
	<étudiant code="E3">
		<nom>Jallouli</nom>
		<prénom>Jalloul</prénom>
		<age>27</age>
		<tél type = "fixe">035000002</tél>
		<tél type ="portable">067000002</tél>
		<email>jallouli@hotmail.com</email>
		<photo source="jallouli.jpg"></photo>
		<CV file = "jallouli.doc" />
		</étudiant>
	<étudiant code="E4">
		<nom>Kaslani</nom>
		<prénom>Kassoul</prénom>
		<age>35</age>
		<tél type = "fixe">035444444</tél>
		<tél type = "portable">063444444</tél>
		<tél type = "portable">067444444</tél>
		<email>kaslani2007@caramail.com</email>
		<photo source="kaslani.jpg"></photo>
		<description>Kaslani Kassoul est l'étudiant le plus ancien de la fac des sciences. Il a changé plusieurs fois d'orientation. Il se prépare cette année pour valider au moins un module (niveau 2ème année de 1er cycle).</description>
	</étudiant>
</liste>
